@echo off
echo Initializing Git repository...
git init
echo Staging files...
git add .
echo Creating commit...
git commit -m "Initial commit"
echo Renaming branch to main...
git branch -M main
echo Setting remote origin...
git remote remove origin 2>nul
git remote add origin https://github.com/orange-otter/Pac-Man.git
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
